export RETRO_ROOTDIR=${RETRO_PATH:-results/}${RETRO_AGENT}-${RETRO_CONF}-${RETRO_GAMESFILE}/
export RETRO_LOGDIR=$RETRO_ROOTDIR
export RETRO_CHECKPOINTDIR=$RETRO_LOGDIR/tensorflow 
mkdir $RETRO_LOGDIR && \
mkdir $RETRO_LOGDIR/tensorflow && \
RETRO_RECORDDIR=$RETRO_ROOTDIR python ${RETRO_AGENT}_agent.py >> $RETRO_LOGDIR/main.log 2>&1
